### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by JellyBrick** [KiwiTalk/loco.rs#2]
- [ ] 스트림 래퍼
- [ ] 패킷
- [ ] 이벤트 디스패칭
- [ ] 추상화 레이어
  - [ ] 기본 Struct
    - [ ] 공지 (ChannelBoardMeta)
      - 없음 (0)
      - 위에 뜨는 공지 (1)
      - 톡 게시판에 기록된 공지 (2)
      - 접은 공지 (3)
- [ ] 오픈챗 링크 (OpenLink)
- [ ] 구성원 (Member)
  - NotFriend, Deactivated, Friend, OpenProfile
    - [ ] 위 타입에 따라서 enum 구성
- [ ] 로그인 데이터 (LoginAccessData)
- [ ] 클라이언트 설정 (ClientSettings)
- [ ] 채팅 로그 (ChatLog)
- [ ] 채팅방 (ChatData)
